# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield', models.CharField(max_length=255)),
                ('emailfield', models.EmailField(max_length=254)),
                ('slugfield', models.SlugField()),
                ('urlfield', models.URLField()),
                ('commaseparatedintegerfield', models.CommaSeparatedIntegerField(max_length=255)),
                ('textfield', models.TextField()),
                ('smallintegerfield', models.SmallIntegerField()),
                ('positivesmallintegerfield', models.PositiveSmallIntegerField()),
                ('integerfield', models.IntegerField()),
                ('positiveintegerfield', models.PositiveIntegerField()),
                ('bigintegerfield', models.BigIntegerField()),
                ('floatfield', models.FloatField()),
                ('timefield', models.TimeField()),
                ('datefield', models.DateField()),
                ('datetimefield', models.DateTimeField()),
                ('booleanfield', models.BooleanField()),
                ('nullbooleanfield', models.NullBooleanField()),
                ('genericipaddressfield', models.GenericIPAddressField()),
                ('filepathfield', models.FilePathField()),
                ('filefield', models.FileField(upload_to='')),
                ('imagefield', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BulkRelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='bulkmodel',
            name='foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreignkey', to='test_app.BulkRelatedModel'),
        ),
    ]
